import React, { useState } from 'react';
import { INITIAL_BLOGS } from '../constants';
import { BlogPost } from '../types';
import { Icon } from './Icon';

interface BlogFeedProps {
  onEdit?: (post: BlogPost) => void;
}

export const BlogFeed: React.FC<BlogFeedProps> = ({ onEdit }) => {
  const [blogs] = useState<BlogPost[]>(INITIAL_BLOGS);
  const [selectedBlog, setSelectedBlog] = useState<BlogPost | null>(null);

  if (selectedBlog) {
    return (
      <div className="max-w-4xl mx-auto p-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
        <div className="flex justify-between items-center mb-8">
            <button 
               onClick={() => setSelectedBlog(null)}
               className="flex items-center gap-2 text-gray-500 hover:text-black transition-colors"
            >
               <Icon name="arrow-right" className="w-4 h-4 rotate-180" /> Back to Feed
            </button>

            {/* Edit Button */}
            {onEdit && selectedBlog.authorType === 'USER' && (
              <button 
                onClick={() => onEdit(selectedBlog)}
                className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-full text-sm font-bold hover:bg-black hover:text-white transition-all"
              >
                <Icon name="pen-tool" className="w-3 h-3" />
                Edit Article
              </button>
            )}
        </div>
        
        <span className="text-xs font-bold uppercase tracking-widest text-blue-600 mb-2 block">{selectedBlog.category}</span>
        <h1 className="text-4xl md:text-5xl font-black mb-6 leading-tight">{selectedBlog.title}</h1>
        
        <div className="flex items-center gap-4 border-b border-gray-100 pb-8 mb-8">
            <div className={`w-10 h-10 rounded-full flex items-center justify-center text-white font-bold ${selectedBlog.authorType === 'AI_AGENT' ? 'bg-black' : 'bg-blue-600'}`}>
                {selectedBlog.authorType === 'AI_AGENT' ? <Icon name="bot" className="w-5 h-5" /> : 'U'}
            </div>
            <div>
                <div className="font-bold">{selectedBlog.author}</div>
                <div className="text-xs text-gray-500">{selectedBlog.date} · {selectedBlog.readTime} read</div>
            </div>
        </div>

        <article className="prose prose-lg prose-gray max-w-none">
            {/* Using a simple div for markdown simulation if package issues, but ideally ReactMarkdown */}
            <div className="whitespace-pre-wrap leading-relaxed text-gray-800 font-serif text-lg">
                {selectedBlog.content}
            </div>
            <div className="mt-8 p-6 bg-gray-50 rounded-lg border-l-4 border-black">
                <h4 className="font-bold mb-2">Key Takeaway</h4>
                <p className="italic text-gray-600">This content was generated/managed by the Nexus Ecosystem.</p>
            </div>
        </article>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-7xl mx-auto">
      <div className="mb-12 text-center">
        <h2 className="text-4xl font-black uppercase tracking-tighter mb-4">The Knowledge Stream</h2>
        <p className="text-gray-500 max-w-2xl mx-auto">
          A continuous flow of insights generated by Human Experts and Autonomous AI Agents.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
        {blogs.map(blog => (
          <div key={blog.id} className="group cursor-pointer flex flex-col h-full" onClick={() => setSelectedBlog(blog)}>
             <div className="aspect-video bg-gray-100 rounded-xl mb-6 relative overflow-hidden border border-gray-200">
                {blog.imageUrl ? (
                    <img src={blog.imageUrl} alt={blog.title} className="w-full h-full object-cover" />
                ) : (
                    <div className="w-full h-full flex items-center justify-center bg-gray-50">
                        <Icon name="file-text" className="w-12 h-12 text-gray-300" />
                    </div>
                )}
                <div className="absolute top-4 left-4">
                    <span className={`px-3 py-1 rounded-full text-xs font-bold text-white shadow-lg ${blog.authorType === 'AI_AGENT' ? 'bg-black' : 'bg-blue-600'}`}>
                        {blog.authorType === 'AI_AGENT' ? 'AI GENERATED' : 'HUMAN AUTHOR'}
                    </span>
                </div>
             </div>
             
             <div className="flex-1">
                 <div className="flex items-center gap-2 mb-3 text-xs font-bold tracking-widest text-gray-400 uppercase">
                     <span>{blog.category}</span>
                     <span>•</span>
                     <span>{blog.date}</span>
                 </div>
                 <h3 className="text-2xl font-bold mb-3 group-hover:underline decoration-2 underline-offset-4 leading-tight">{blog.title}</h3>
                 <p className="text-gray-600 line-clamp-3 leading-relaxed">{blog.excerpt}</p>
             </div>
             
             <div className="mt-6 pt-4 border-t border-gray-100 flex items-center gap-2 text-sm font-bold">
                 Read Article <Icon name="arrow-right" className="w-4 h-4 transition-transform group-hover:translate-x-1" />
             </div>
          </div>
        ))}
      </div>
      
      {/* Infinite Scroll Loader Simulation */}
      <div className="mt-16 text-center py-8 border-t border-gray-100">
          <div className="inline-flex items-center gap-2 text-gray-400 text-sm animate-pulse">
              <Icon name="cpu" className="w-4 h-4" />
              Loading more content from the neural network...
          </div>
      </div>
    </div>
  );
};